AarhusWebDevCoop/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace AarhusWebDevCoop.ViewModels
{
    public class ContactForm
    {
        [Required]
        public string Name {get; set; }

        [Required]
        [EmailAddress(ErrorMessage = "This is not a valid email")]
        public string Email { get; set; }

        [Required]
        public string Subject { get; set; }

        [Required]
        public string Message { get; set; }
    }
}

AarhusWebDevCoop/ViewModels/MessageBoard.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace AarhusWebDevCoop.ViewModels
{
    public class MessageBoard
    {
        [Required(ErrorMessage = "A name is required")]
        public string Name { get; set; }

        [Required(ErrorMessage = "A message is required")]
        [DataType(DataType.MultilineText)]
        public string Message { get; set; }
    }
}

AarhusWebDevCoop/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using AarhusWebDevCoop.ViewModels;
using System.Net.Mail;
using System.Net;
using Umbraco.Core.Models;

namespace AarhusWebDevCoop.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        // GET: ContactFormSurface
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactForm());
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {
            if
                (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }

            MailMessage message = new MailMessage();
            message.To.Add("mikkelvba@gmail.com");
            message.Subject = model.Subject;
            message.From = new MailAddress(model.Email, model.Name);
            message.Body = model.Message + "\n Email: " + model.Email;

            using (SmtpClient smtp = new SmtpClient())
            {
                smtp.DeliveryMethod = SmtpDeliveryMethod.Network;
                smtp.UseDefaultCredentials = false;
                smtp.EnableSsl = true;
                smtp.Host = "smtp.gmail.com";
                smtp.Port = 587;
                smtp.Credentials = new NetworkCredential("mikkelvba@gmail.com", "rtuurozchslaijbm");

                smtp.Send(message);
            }
            TempData["success"] = true;

            IContent comment = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "Comment");

            comment.SetValue("commentName", model.Name);
            comment.SetValue("email", model.Email);
            comment.SetValue("subject", model.Subject);
            comment.SetValue("message", model.Message);

            Services.ContentService.Save(comment);
        
            //Redirects to the same page without the data
            return RedirectToCurrentUmbracoPage();
        }
    }
}

AarhusWebDevCoop/Controllers/MessageBoardSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AarhusWebDevCoop.ViewModels;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;

namespace AarhusWebDevCoop.Controllers
{
    public class MessageBoardSurfaceController : SurfaceController
    {
        // GET: MessageBoardSurface
        [HttpGet]
        public ActionResult CreateMessage()
        {
            return PartialView("MessageForm", new MessageBoard());
        }

        [HttpPost]
        public ActionResult CreateMessage(MessageBoard messageBoard)
        {
            if (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }
            IContent msg = Services.ContentService.CreateContent(messageBoard.Name, CurrentPage.Id, "messageBoard");

            msg.SetValue("msgbName", messageBoard.Name);
            msg.SetValue("msgbMessage", messageBoard.Message);
            try
            {
                //Saves but doesnt publish IContent
                //Services.ContentService.Save(msg);

                //Saves and publish IContent
                Services.ContentService.SaveAndPublishWithStatus(msg);
            }
            catch (Exception e)
            {
                TempData["TempMsgBoard"] = "<div class='alert alert-danger'><p>Message was not created</p>" + "<p>Something went wrong. Try again later or contact your administrator.</p></div>";
                ModelState.AddModelError(string.Empty, "" + e.InnerException.ToString());
            }
            TempData["TempMsgBoard"] = "<div class='alert alert-success'><p>Message was created</p>" + "<p>You have succesfully created a message.</p></div>";
            return RedirectToCurrentUmbracoPage();
        }

        [HttpPost]
        public ActionResult DeleteMessage(int contentId, int redirectId)
        {
            var cs = Services.ContentService;
            var msg = cs.GetById(contentId);
            if (msg != null)
            {
                try
                {
                    cs.Delete(msg);
                }
                catch (Exception e)
                {
                    TempData["TempMsgBoard"] = "<div class='alert alert-danger'><p>Message was not deleted</p>" + "<p>Something went wrong. Try again later or contact your administrator.</p></div>";
                    ModelState.AddModelError(string.Empty, "" + e.InnerException.ToString());
                }
            }
            TempData["TempMsgBoard"] = "<div class='alert alert-success'><p>Message was deleted</p>" + "<p>You have succesfully deleted a message.</p></div>";
            return RedirectToUmbracoPage(redirectId);
            //return RedirectToCurrentUmbracoPage();
        }
    }
}

AarhusWebDevCoop/Views/ArticlesItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticlesItem>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<div id="main-container">
    <div id="main" class="wrapper clearfix">
        <section>
			<div class="message-board">
				<h1>@Umbraco.Field("articleTitle")</h1>
			</div>
			<div class="article-content">
				@Umbraco.Field("articleContent")
			</div>
		</section>  
    </div> <!-- #main -->
</div> <!-- #main-container -->

AarhusWebDevCoop/Views/ArticlesMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ArticlesMain>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}

<div id="main-container">
    <div id="main" class="wrapper clearfix">
        <section>
		<div class="message-board">
            <h1>@Umbraco.Field("articlesTitle")</h1>
		</div>
        @Umbraco.Field("articlesBodyText")
        </section>
		@Umbraco.RenderMacro("listArticles")
    </div> <!-- #main -->
</div> <!-- #main-container -->

AarhusWebDevCoop/Views/ContactFormSurface/ContactForm.cshtml
@model AarhusWebDevCoop.ViewModels.ContactForm
@{
    Layout = null;
}

@if (TempData["success"] == null)
{
    using (Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new object { }, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
                @Html.ValidationMessageFor(m => m.Subject)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextAreaFor(m => m.Message, new { @class = "form-control", placeholder = "Message" })
                @Html.ValidationMessageFor(m => m.Message)
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label">Submit</label>
            <div class="col-sm-6">
                <button id="contact-submit" type="submit" class="btn btn-primary input-medium pull-left">Submit</button>
            </div>
        </div>
    }
}
else
{
<div class="alert alert-success">
    <p>Thank you for contacting us. We’ll be in touch soon!</p>
</div>
}

AarhusWebDevCoop/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.ContactPage>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<div class="intro">
	<div class="row">
		<div class="col-lg-12 col-md-12">
			<div class="site-heading contact-form">
				<h1>@CurrentPage.Name</h1>
				<div>
					@Html.Action("Index", "ContactFormSurface")
				</div>
			</div>
		</div>
	</div>
</div>

AarhusWebDevCoop/Views/Home.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Home>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<div class="frontpage-intro intro">
	<div class="row">
		<div class="col-lg-12 col-md-12">
			<div class="site-heading">
				<h1>@Umbraco.Field("siteTitle")</h1>
				<h2>@Umbraco.Field("mainContent")</h2>
			</div>
		</div>
	</div>
</div>
				
<div class="container home-projects">
    <div id="main" class="wrapper clearfix">
        <section>
            @CurrentPage.GetGridHtml("Grid")
        </section>  
    </div> <!-- #main -->
</div> <!-- #main-container -->
		
@Umbraco.RenderMacro("twoNewestCompletedProjects")

AarhusWebDevCoop/Views/Login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers
@using Umbraco.Web
@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@{
	Layout = "Master.cshtml";
}

<div class="intro">
	<div class="row">
		<div class="col-lg-12 col-md-12">
			<div class="site-heading login-form">
			@Html.RenderJsHere()

			@if (!Members.GetCurrentLoginStatus().IsLoggedIn) {
				@Html.Partial("Login");
			}
			else 
			{
				@Html.Partial("Logout");

			}
			</div>
		</div>
	</div>
</div>

AarhusWebDevCoop/Views/MacroPartials/listArticles.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
	
	
@{ var selection = CurrentPage.Children.Where("Visible").OrderBy("CreateDate desc"); }
@* OrderBy() takes the property to sort by and optionally order desc/asc *@

@foreach (var item in selection)
{
	<div class="list-group">
	  <a href="@item.Url" class="list-group-item">
		<h4 class="list-group-item-heading">@item.Name</h4>
		<p class="list-group-item-text">@Umbraco.Truncate(@item.articleContent,100)</p>
	  </a>
	</div>
}

AarhusWebDevCoop/Views/MacroPartials/listMessages.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@{ var selection = CurrentPage.Children.Where("Visible").OrderBy("CreateDate desc"); }
@* OrderBy() takes the property to sort by and optionally order desc/asc *@

@foreach (var item in selection)
{
<div class="col-md-4 col-xs-12">
    <div class="panel panel-default">
        <div class="panel-heading ">
            <h4>@item.msgbName</h4>
            @using (Html.BeginForm("DeleteMessage", "MessageBoardSurFace", new { contentId = @item.Id, redirectId = CurrentPage.Id }, FormMethod.Post, new { @class = "form-inline" }))
            {
                <button id="" type="submit" class="btn btn-xs btn-danger">Remove</button>
            }
        </div>
        <div class="panel-body">
            @item.msgbMessage
        </div>
    </div>
</div>
}

AarhusWebDevCoop/Views/MacroPartials/listProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@{ var selection = CurrentPage.Children.Where("Visible").OrderBy("CreateDate desc"); }
@* OrderBy() takes the property to sort by and optionally order desc/asc *@

    @foreach (var item in selection)
    {
		<div class="list-group row">
			<a href="@item.Url" class="list-group-item">
				<div class="col-lg-4">
					<img class="img-responsive" src="@Umbraco.Media(item.image).Url"/>
				</div>
				<div class="col-lg-8">
					<h4 class="list-group-item-heading">@item.Name</h4>
					<p class="list-group-item-text">@Umbraco.Truncate(@item.projectContent,100)</p>
					<p class="list-group-item-text status">Status: @item.status</p>
				</div>
			</a>
		</div>
    }

AarhusWebDevCoop/Views/MacroPartials/mainMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers
@{
    var selection = CurrentPage.Site().Children.Where("Visible && DocumentTypeAlias != \"projectsMain\"");
    var projects = CurrentPage.Site().Children.Where("DocumentTypeAlias == \"projectsMain\"").First().Children.OrderBy("UpdateDate descending").Take(2);
	var loginStatusModel = Members.GetCurrentLoginStatus();
}
<nav>
    <div class="navbar navbar-inverse navbar-static-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/">Aarhus Web Dev</a>
            </div>
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    @foreach (var item in selection)
                    {
                        <li>
                            <a href="@item.Url">@item.Name</a>
                        </li>
                    }
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#">
                            Projects
                            <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li>
                                <a href="/projects">Projects</a>
                            </li>
                            <li role="separator" class="divider"></li>
                            @foreach (var item in projects)
                            {
                                if (@item.Status == "Completed")
                                {
                                    <li>
                                        <a href="@item.Url">@item.Name</a>
                                    </li>
                                }
                            }
                        </ul>
                    </li>
                </ul>
				<ul class="nav navbar-nav navbar-right">
					@if (!Members.GetCurrentLoginStatus().IsLoggedIn) {
						<li><a href="/login">Login</a></li>
					}
					else 
					{
						<li><a href="/login">Logout</a></li>
					}
				</ul>	
            </div>
        </div>
    </div>
</nav>

AarhusWebDevCoop/Views/MacroPartials/memberService.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
	var memberService = ApplicationContext.Current.Services.MemberService;
	var members = memberService.GetMembersByGroup("Active");
}

@foreach (var member in members)
{
    string fullPath = member.GetValue("photo").ToString();
    string[] substrings = fullPath.Split(',');
    string srcString = substrings[2];
    string[] srcSubStrings = srcString.Split(':');
    string srcPath = srcSubStrings[1].Replace("\"", "");
    srcPath = srcPath.Replace("}", "");
    <div class="list-members">
        <div class="col-lg-4 col-md-4">
            <img class="img-responsive" src="@srcPath" />
        </div>
        <div class="col-lg-8 col-md-8">
            <p>
                @(member.GetValue("firstname") + " " + member.GetValue("lastname")) <br />
                @member.GetValue("address")<br />
                @(member.GetValue("zip") + " " + member.GetValue("city"))<br />
                Mobile: @member.GetValue("mobile")
            </p>
        </div>
    </div>
}

AarhusWebDevCoop/Views/MacroPartials/twoNewestCompletedProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@{ var projects = Umbraco.Content(1136);}
@* OrderBy() takes the property to sort by and optionally order desc/asc *@

<div class="row page-content">
	<h2 class="title">Two newest projects</h2>
	<hr class="small">
	@foreach (var child in projects.Children.OrderBy("CreateDate").Where("Status.Contains(\"Completed\")").Take(2)) {
	<a href="@child.Url">
		<div class="col-md-6">
			<div class="fp-images">
				<img class="img-responsive" src="@Umbraco.Media(child.image).Url"/>
			</div>
			<h3>@child.projectTitle</h3>
			@Umbraco.Truncate(@child.projectContent,200)
		</div>
	</a>
	}
</div>

AarhusWebDevCoop/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
	Layout = null;
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Umbraco</title>

    <link rel="stylesheet" href="/Content/bootstrap.min.css">
    <link rel="stylesheet" href="/Content/bootstrap-theme.min.css">
    <link rel="stylesheet" href="/css/style.css">

    <link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Poppins">
    
</head>

<body>
	
    <div id="headercontainer">
        <header class="wrapper clearfix">
            <nav>
				@Umbraco.RenderMacro("mainMenu")
			</nav>
		</header>
	</div>
			
	<main class="container">
		@RenderBody()
	</main>
			
    <footer id="footer">
        <div class="container text-center">
			<p class="text-muted credit">@Umbraco.Field("footerText", recursive: true)</p>
		</div>
	</footer>
			
<script src="/scripts/jquery-3.1.0.min.js"></script>
<script src="/scripts/bootstrap.min.js"></script>
<script src="~/scripts/jquery.validate.min.js"></script>
<script src="~/scripts/jquery.validate.unobtrusive.min.js"></script>
</body>
</html>

AarhusWebDevCoop/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Members>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<div class="full-list-members">
	@Umbraco.RenderMacro("memberService")
</div>

AarhusWebDevCoop/Views/MessageBoard.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.MessageBoard>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = "Master.cshtml";
}
<div class="message-board">
	<h1>Message board</h1>

	@Html.Action("CreateMessage", "MessageBoardSurface")

	@Html.Raw(TempData["TempMsgBoard"])
	<section>
		@Umbraco.RenderMacro("listMessages")
	</section>
</div>

AarhusWebDevCoop/Views/MessageBoardSurface/MessageForm.cshtml
@model AarhusWebDevCoop.ViewModels.MessageBoard

@{
    Layout = null;
}

@using (Html.BeginUmbracoForm("CreateMessage", "MessageBoardSurFace", new object { }, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Message, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Message, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Message, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

AarhusWebDevCoop/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

AarhusWebDevCoop/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))